#!/usr/bin/python

import sys
import getopt

sys.path.append( 'lib' )

import authenticate

def parse_cmdline(argv):

  usage = """\
USAGE: login [OPTIONS] username password
Available Options
  -h [ --help ]      Print this message
"""

  shortOpts = "h"
  longOpts = ['help']
  opts = ()
  args = ()

  account_info = {}
  account_info['username'] = False
  account_info['password'] = False

  try:
    opts,args = getopt.gnu_getopt(argv,shortOpts,longOpts)
  except getopt.GetoptError:
    sys.stderr.write(usage)
    sys.exit(1)

  for opt, val in opts:
    if opt in ('-h','--help'):
      sys.stdout.write(usage)
      sys.exit(0)

  if len(args) != 2:
    sys.stderr.write("ERROR! Please specify a username password\n")
    sys.stderr.write(usage)
    sys.exit(0)

  account_info['username'] = args[0]
  account_info['password'] = args[1]

  return (account_info)

if __name__ == "__main__":

  account_info = parse_cmdline(sys.argv[1:])
  json = authenticate.login( account_info )
  if json['status'].startswith('login_'):
    print '%s %s' % ( json['message'], json['session_id'] )
  elif json['status'] == 'error':
    print 'Error: %s' % ( json['message'] )
  else:
    print "Unknown error occurred"

# End
