#!/usr/bin/python

import sys
import getopt

sys.path.append( 'lib' )

import authenticate

def parse_cmdline(argv):

  usage = """\
USAGE: logout [OPTIONS]
Available Options
  -h [ --help ]      Print this message
"""

  shortOpts = "h"
  longOpts = ['help']
  opts = ()
  args = ()

  try:
    opts,args = getopt.gnu_getopt(argv,shortOpts,longOpts)
  except getopt.GetoptError:
    sys.stderr.write(usage)
    sys.exit(1)

  for opt, val in opts:
    if opt in ('-h','--help'):
      sys.stdout.write(usage)
      sys.exit(0)

if __name__ == "__main__":

  parse_cmdline(sys.argv[1:])
  authenticate.logout()

# End
